bf16: false
cutoff_len: 32
dataloader_num_workers: 0
dataloader_pin_memory: false
dataset: medalpaca
dataset_dir: ./llama_factory_data/data
ddp_find_unused_parameters: false
ddp_timeout: 18000
do_train: true
eval_steps: 10
finetuning_type: lora
flash_attn: fa2
fp16: true
gradient_accumulation_steps: 32
gradient_checkpointing: true
learning_rate: 0.0001
load_best_model_at_end: false
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
lora_target: q_proj,v_proj
low_cpu_mem_usage: true
lr_scheduler_type: linear
max_grad_norm: 0.5
max_samples: 2
model_name_or_path: Qwen/Qwen3-VL-8B-Instruct
num_train_epochs: 1
optim: adamw_8bit
output_dir: ./llama_factory_data/medical_qwen3_output
overwrite_cache: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: false
preprocessing_num_workers: 0
quantization_bit: 4
quantization_method: bitsandbytes
remove_unused_columns: true
report_to: []
run_name: medical_qwen3_lora_optimized
save_on_each_node: true
save_steps: 10
save_strategy: steps
save_total_limit: 1
stage: sft
template: qwen3_vl_nothink
tf32: false
torch_empty_cache_steps: 1
trust_remote_code: true
upcast_layernorm: true
use_unsloth: true
warmup_ratio: 0.05
weight_decay: 0.01
